name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is running on @{{runner.os}}"
      - run: echo "The triggering event is @{{github.event_name}}"
      - run: echo "The current branch is ${{github.ref}}"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v