name: learn-github-actions
on: [push]
jobs:
  running-python-script:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is running on ${{ runner.os }}"
      - run: echo "The triggering event is ${{ github.event_name }}"
      - run: echo "The current branch is ${{ github.ref }}"
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            print("Directory contents:")
            print([f for f in os.listdir()])
      - name: execute py script 
        run: |
            python get_blobs.py
        